// <auto-generated />
using System;
using EF.Server.REST.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.Server.REST.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181121172539_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF.Server.REST.Models.Objects.OGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Values");

                    b.HasKey("Id");

                    b.ToTable("OGrade");
                });

            modelBuilder.Entity("EF.Server.REST.Models.Objects.OStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Born");

                    b.Property<string>("Name");

                    b.Property<string>("PESEL");

                    b.HasKey("Id");

                    b.ToTable("OStudent");
                });

            modelBuilder.Entity("EF.Server.REST.Models.Objects.OSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("OSubject");
                });

            modelBuilder.Entity("EF.Server.REST.Models.Relations.RStudentSubject", b =>
                {
                    b.Property<Guid>("StudentId");

                    b.Property<Guid>("SubjectId");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("RStudentSubject");
                });

            modelBuilder.Entity("EF.Server.REST.Models.Relations.RStudentSubject", b =>
                {
                    b.HasOne("EF.Server.REST.Models.Objects.OStudent", "Student")
                        .WithMany("RStudentsSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.Server.REST.Models.Objects.OSubject", "Subject")
                        .WithMany("RStudentsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
